on: [push, pull_request]
jobs:
  filename_check:
    runs-on: ubuntu-latest
    name: check filenames
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        # assume a maximum of 10 commits in a simple PR
        fetch-depth: 10
    - name: Filename Check
      uses: ./.github/actions/file-check
